repository_type: pipeline

nf_core_version: 4.1.0

lint:
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-organelleauth_logo_light.png
    - docs/images/nf-core-organelleauth_logo_light.png
    - docs/images/nf-core-organelleauth_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - assets/email_template.txt
    - docs/README.md
  nextflow_config:
    - manifest.name
  multiqc_config:
    - report_comment
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-organelleauth_logo_light.png
    - docs/images/nf-core-organelleauth_logo_light.png
    - docs/images/nf-core-organelleauth_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml

template:
  org: LinweiLi
  name: organelleauth
  description: TCM organelle genome authentication system
  author: LinweiLi
  version: 0.1.0dev
  force: true
  outdir: /home/iris-hp/Project/organelle-auth-staging
  is_nfcore: false
